version: "3.8"
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ../db:/data/db
    
  app:
    depends_on:
      - mongodb
    build: .
    env_file: ./.env
    restart: unless-stopped
    ports:
      - 3000:6521
    environment:
      - PORT=3000
      -
      - MONGO_URL=mongodb://root:root@mongodb:27017/
      - PASERK_PUB=$PASERK_PUB
      - PASERK_SECRET=$PASERK_SECRET
      - GMAIL_ID=$GMAIL_ID
      - GMAIL_PASSWORD=$GMAIL_PASSWORD
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_BUCKET_NAME=$AWS_BUCKET_NAME
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    stdin_open: true
    tty: true